// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	job "github.com/antgubarev/pet/internal/job"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ControllerI is an autogenerated mock type for the ControllerI type
type ControllerI struct {
	mock.Mock
}

// Finish provides a mock function with given fields: id
func (_m *ControllerI) Finish(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: j, args
func (_m *ControllerI) Start(j *job.Job, args job.StartArguments) (*job.Execution, error) {
	ret := _m.Called(j, args)

	var r0 *job.Execution
	if rf, ok := ret.Get(0).(func(*job.Job, job.StartArguments) *job.Execution); ok {
		r0 = rf(j, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*job.Execution)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*job.Job, job.StartArguments) error); ok {
		r1 = rf(j, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
