run:
  concurrency: 4
  timeout: 5m

skip-dirs:
  - .history
  - vendor
  - tests

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  dupl:
    threshold: 100
  maligned:
    suggest-new: true
  misspell:
    locale: US
  funlen:
    lines: 60
    statements: 40
  forbidigo:
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/rs/zerolog
    packages-with-error-message:
      - github.com/sirupsen/logrus: "logging is allowed only by zap"
      - github.com/rs/zerolog: "logging is allowed only by zap"
  godox:
    keywords:
      - FIXME
      - TODO
      - HACK
  staticcheck:
    go: "1.17"
    checks: ["all"]
  errorlint:
    asserts: false

linters:
  enable-all: true
  disable:
    - golint #deprecated
    - scopelint #deprecated
    - maligned #deprecated
    - interfacer # deprecated
    - godox # Not relevant
    - exhaustivestruct # Not relevant
    - wsl # Too strict
    - gofumpt # Not relevant

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - noctx
