builds:
  - id: "jobsrv"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    main: ./cmd/server
    binary: jobsrv
  - id: "jobsexec"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    main: ./cmd/executor
    binary: jobsexec
  - id: "jobsctl"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/ctl
    binary: jobsctl

archives:
  - id: jobs
    builds:
      - "jobsrv"
      - "jobsexec"
      - "jobsctl"
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md
    wrap_in_directory: "true"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  skip: true
