// Code generated by mockery v2.9.4. DO NOT EDIT.

package job

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockExecutionStorage is an autogenerated mock type for the ExecutionStorage type
type MockExecutionStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: execution
func (_m *MockExecutionStorage) Delete(execution *Execution) error {
	ret := _m.Called(execution)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Execution) error); ok {
		r0 = rf(execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByJobName provides a mock function with given fields: jobName
func (_m *MockExecutionStorage) DeleteByJobName(jobName string) error {
	ret := _m.Called(jobName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(jobName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: id
func (_m *MockExecutionStorage) GetById(id uuid.UUID) (Execution, error) {
	ret := _m.Called(id)

	var r0 Execution
	if rf, ok := ret.Get(0).(func(uuid.UUID) Execution); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(Execution)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByJobName provides a mock function with given fields: jobName
func (_m *MockExecutionStorage) GetByJobName(jobName string) ([]Execution, error) {
	ret := _m.Called(jobName)

	var r0 []Execution
	if rf, ok := ret.Get(0).(func(string) []Execution); ok {
		r0 = rf(jobName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Execution)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(jobName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: execution
func (_m *MockExecutionStorage) Store(execution *Execution) error {
	ret := _m.Called(execution)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Execution) error); ok {
		r0 = rf(execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
