// Code generated by mockery v2.9.4. DO NOT EDIT.

package job

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockControllerI is an autogenerated mock type for the ControllerI type
type MockControllerI struct {
	mock.Mock
}

// Finish provides a mock function with given fields: id
func (_m *MockControllerI) Finish(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: j, args
func (_m *MockControllerI) Start(j *Job, args StartArguments) (*Execution, error) {
	ret := _m.Called(j, args)

	var r0 *Execution
	if rf, ok := ret.Get(0).(func(*Job, StartArguments) *Execution); ok {
		r0 = rf(j, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Execution)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*Job, StartArguments) error); ok {
		r1 = rf(j, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
